# Generated by Django 2.1.2 on 2018-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
