# Generated by Django 2.1 on 2018-11-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Accepted'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=9),
        ),
    ]
