# Generated by Django 2.1 on 2018-11-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181113_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceOffer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='app.ServiceOffer'),
            preserve_default=False,
        ),
    ]
