# Generated by Django 2.1 on 2018-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181113_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceOffer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
