# Generated by Django 2.1 on 2018-11-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181113_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serviceOffer',
        ),
    ]
